spring:
  datasource:
    type: com.mysql.cj.jdbc.MysqlDataSource
    url: jdbc:mysql://localhost:3306/student?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: